name: lesson2
description: "Pokemon."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.8.0
  flutter_fortune_wheel: ^1.3.2
  scratcher: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/pokedex/
    - images/pokedex/hires/
    - images/pokedex/sprites/
